### ISSUE TITLE
[Feature Request] Compatibility with Dhizuku

### ISSUE THREAD

**Issue by Userofmyphone** [BinTianqi/OwnDroid#49] opened 2024-07-08 19:10 UTC
Hello. Can you make your OwnDroid app compatible with [Dhizuku](https://github.com/iamr0s/Dhizuku)? Here it is [Dhizuku API](https://github.com/iamr0s/Dhizuku-API.git)

**Comment by Minoricew** [comment] 2024-07-08 23:45
Your issue is a duplicate of #35 and [discussion #23](https://github.com/BinTianqi/OwnDroid/discussions/23). 😂

We are working hard to make OwnDroid support the Dhizuku API, but due to compatibility challenges, it may take some time. Please be patient and stay tuned for updates, thank you for your feedback. ✨

**Closed** 2024-08-14 13:13 UTC
Labels: enhancement
